const STORAGE_NAMESPACE = "GISTMARKS_IO_"

export const AUTH_STORAGE_KEY = STORAGE_NAMESPACE + "AUTH_STORAGE"
export const COLLECTIONS_STORAGE_KEY = STORAGE_NAMESPACE + "COLLECTIONS_STORAGE"
export const BOOKMARK_STORAGE_KEY = STORAGE_NAMESPACE + "BOOKMARK_STORAGE"
