const STORAGE_NAMESPACE = "GISTMARKS_IO:"

export const VIEW_SETTINGS_STORAGE_KEY =
  STORAGE_NAMESPACE + "VIEW_SETTINGS_STORAGE"

export const AUTH_STORAGE_KEY = STORAGE_NAMESPACE + "AUTH_STORAGE"

export const BOOKMARK_STORAGE_KEY = STORAGE_NAMESPACE + "BOOKMARK_STORAGE"

export const GIST_BACKUP_STATE = STORAGE_NAMESPACE + "GIST_BACKUP_STATE"

export const GIST_BACKUP_RESULT_STATE =
  STORAGE_NAMESPACE + "GIST_BACKUP_RESULT_STATE"

export const GIST_RESTORE_STATE = STORAGE_NAMESPACE + "GIST_RESTORE_STATE"
