const STORAGE_NAMESPACE = "GISTMARKS_IO:"

export const SETTINGS_STORAGE_KEY = STORAGE_NAMESPACE + "VIEW_SETTINGS_STORAGE"

export const AUTH_STORAGE_KEY = STORAGE_NAMESPACE + "AUTH_STORAGE"

export const BOOKMARK_STORAGE_KEY = STORAGE_NAMESPACE + "BOOKMARK_STORAGE"

export const BACKUP_STORAGE_KEY = STORAGE_NAMESPACE + "BACKUP_STORAGE"
